#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$cli = new Commando\Command();
$cli->setHelp('Must create a JSON configuration file to specify data transformers - documentation https://github.com/ashleyhindle/private-dump');
$cli->option('u')->aka('user')->description('MySQL Username - overrides value in config file');
$cli->option('p')->aka('password')->description('MySQL Password - overrides value in config file');
$cli->option('h')->aka('host')->description('MySQL Hostname - overrides value in config file');


$bogies = new PrivateDump\Bogies();
// private-dump -u root -p
echo "END" . PHP_EOL;